#!/usr/bin/env python3
"""Check a recomp repo for material that must not be published.

Run before making a project public. It answers one question: is anything
tracked by git that is not our own work?

    python tools/audit_repo.py ../bolo ../coaster ../nocturne

Three categories, in descending order of how much trouble they are:

  game material   The original binary, its DLLs, a disc image, extracted
                  assets. Never acceptable. Every project in this family says
                  "bring your own disc" and has to mean it.

  lifted output   Generated C. This is the one people miss, because it looks
                  like source we wrote. It is not: lifting a binary produces a
                  derivative work of that binary, so the output carries
                  whatever licence the original does. Every public repo in
                  this family tracks zero lifted files.

  history         Both of the above, in commits that are no longer HEAD.
                  Deleting a file does not un-publish it -- a public repo
                  exposes its whole history, and `git log -p` is one command.
                  This is the failure that looks fixed and is not.

Derived *metadata* is fine and normal: function addresses, vtable lists,
IDA exports. The public repos ship those (gta 7 files, crimsonskies 5). The
line is between facts about the binary and a copy of it.
"""
import argparse
import os
import subprocess
import tempfile
import sys
from collections import Counter

GAME_BIN = {".exe", ".dll", ".ovl", ".com", ".sys", ".drv", ".vxd", ".ocx",
            ".iso", ".bin", ".cue", ".img", ".ima", ".mdf", ".ccd", ".nrg",
            ".cab", ".arj", ".lzh", ".z"}
GAME_ASSET = {".pic", ".act", ".pcx", ".lbm", ".tga", ".wav", ".voc", ".mid",
              ".mus", ".xmi", ".mp3", ".ogg", ".avi", ".mpg", ".smk", ".flc",
              ".fli", ".pak", ".pk3", ".wad", ".grp", ".res", ".rez", ".vol",
              ".gob", ".lfd", ".m20", ".mvb", ".fif", ".dat"}
# Screenshots of our own port belong in docs/. Anything else of these types is
# the game's art until proven otherwise.
#
# "In docs/" is weak evidence, not proof, and this tool cannot tell a
# screenshot of your renderer from the game's own artwork re-encoded as a PNG.
# Both are pixels in a file. The Force Commander teardown produced exactly that
# trap: a 640x480 BITMAP lifted straight out of the executable's .rsrc, written
# to docs/img/splash.png, which this auditor called clean because of where it
# sat. It was a byte-exact copy of LucasArts' artwork.
#
# So docs/ images are reported for review rather than passed in silence.
IMAGE = {".png", ".jpg", ".jpeg", ".gif"}

LIFTED_HINTS = ("recompiledfuncs/", "/recomp/gen/", "recomp_0", "/seg0", "/seg1",
                "_dispatch.c", "_unresolved_stubs.c", "lifted_")
# What a generated file says about itself, checked when the path is ambiguous.
LIFTED_MARKERS = (b"Auto-generated", b"auto-generated", b"Generated by",
                  b"generated by ne_lift", b"generated by lift")
# Saying "auto-generated" is not enough to be a copy. A generated table of
# declarations or segment bases is derived metadata, which this document's own
# rule allows: a list of addresses is a fact, the instructions at those
# addresses are a copy. So a generated file also has to carry the guest's
# instructions, which means it drives the CPU model. elfish's segments.h is
# 445KB of `void segN_X(CPU *cpu);` and was reported as lifted output on the
# strength of its header line alone.
GUEST_CODE = (b"cpu->", b"ctx->r", b"mem_write", b"mem_read")
# `RECOMP_GENERATED_CODE` is deliberately not in that list: it is the macro
# environment lifted code compiles in, and a hand-written shim defines it too in
# order to use ARG()/RET(). fury3 and pod-recomp both ship a
# src/runtime/shims_impl.c that opens with "hand-written import shims", goes on
# to mention the "auto-generated stubs" it replaces -- which is what trips
# LIFTED_MARKERS -- and then drives the CPU model, because that is what a shim
# in this model does. No property of the content separates those two, so take a
# file at its word when it says it was written by hand.
HAND_WRITTEN = (b"hand-written", b"Hand-written", b"hand written",
                b"hand-implemented", b"NOT auto-generated")


def git(repo, *args):
    return subprocess.run(["git", "-C", repo, *args],
                          capture_output=True, text=True).stdout


def looks_lifted(repo, path):
    if any(h in path.lower() for h in LIFTED_HINTS):
        return True
    if not path.endswith((".c", ".h")):
        return False
    full = os.path.join(repo, path)
    try:
        with open(full, "rb") as f:
            head = f.read(65536)
    except OSError:
        return False
    if any(m in head[:600] for m in HAND_WRITTEN):
        return False
    if not any(m in head[:400] for m in LIFTED_MARKERS):
        return False
    return any(m in head for m in GUEST_CODE)


def human(n):
    for u in ("B", "KB", "MB", "GB"):
        if n < 1024:
            return f"{n:.0f}{u}"
        n /= 1024
    return f"{n:.0f}TB"


def audit(repo):
    files = [f for f in git(repo, "ls-files").splitlines() if f]
    if not files:
        return None
    game, lifted, review = [], [], []
    for f in files:
        ext = os.path.splitext(f)[1].lower()
        full = os.path.join(repo, f)
        size = os.path.getsize(full) if os.path.exists(full) else 0
        if ext in GAME_BIN or ext in GAME_ASSET:
            game.append((f, size))
        elif ext in IMAGE:
            (review if f.lower().startswith("docs/") else game).append((f, size))
        elif looks_lifted(repo, f):
            lifted.append((f, size))

    # History: the same question, asked of every object ever committed.
    hist = Counter()
    for ln in git(repo, "rev-list", "--objects", "--all").splitlines():
        parts = ln.split(" ", 1)
        if len(parts) != 2:
            continue
        p = parts[1]
        ext = os.path.splitext(p)[1].lower()
        if ext in GAME_BIN or ext in GAME_ASSET:
            hist["game material"] += 1
        elif any(h in p.lower() for h in LIFTED_HINTS):
            hist["lifted output"] += 1
    return files, game, lifted, review, hist


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("repos", nargs="*", help="paths to git repos")
    ap.add_argument("-v", "--verbose", action="store_true",
                    help="list every flagged file, not just the first few")
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        demo()
        return 0
    if not args.repos:
        ap.error("give at least one repo path (or --selftest)")

    worst = 0
    for repo in args.repos:
        name = os.path.basename(os.path.abspath(repo))
        r = audit(repo)
        if r is None:
            print(f"\n{name}: not a git repo, or nothing tracked")
            continue
        files, game, lifted, review, hist = r
        print(f"\n{'=' * 64}\n{name}  ({len(files)} tracked files)")
        for label, items in (("GAME MATERIAL", game), ("LIFTED OUTPUT", lifted)):
            if items:
                total = sum(s for _, s in items)
                print(f"  !! {label}: {len(items)} files, {human(total)}")
                show = items if args.verbose else sorted(items, key=lambda x: -x[1])[:5]
                for f, s in show:
                    print(f"       {human(s):>8}  {f}")
                if not args.verbose and len(items) > 5:
                    print(f"       ... and {len(items) - 5} more (-v for all)")
        if hist:
            print("  !! IN HISTORY (deleting from HEAD does not remove these):")
            for k, n in hist.most_common():
                print(f"       {n:>6} objects  {k}")
        if review:
            total = sum(s for _, s in review)
            print(f"  ?? REVIEW: {len(review)} image(s) in docs/, {human(total)}")
            print("       Your own screenshots are fine. The game's artwork is not,")
            print("       and this tool cannot tell them apart -- check these by eye.")
            for f, s in sorted(review, key=lambda x: -x[1])[:5]:
                print(f"       {human(s):>8}  {f}")
        if not game and not lifted and not hist:
            print("  CLEAN -- nothing tracked but our own work"
                  + (", but see REVIEW above" if review else ""))
        else:
            worst = 1
    if worst:
        print("\nSee docs/PUBLISHING.md for how to strip these before going public.")
    return worst


def demo():
    """One runnable check: the classifier, on the shapes that actually occur."""
    assert looks_lifted(".", "RecompiledFuncs/coaster_recomp_015.c")
    assert looks_lifted(".", "src/recomp/gen/recomp_0023.c")
    assert looks_lifted(".", "src/seg002.c")
    assert looks_lifted(".", "src/_dispatch.c")
    # Hand-written runtime code is not lifted output and must not be flagged.
    assert not looks_lifted(".", "runtime/win16/ne_resources.c")
    assert not looks_lifted(".", "tools/parse_map.py")

    # When the path gives nothing away the file gets read, so these four need
    # real files. All four are shapes that occur in the public repos today.
    with tempfile.TemporaryDirectory() as d:
        def w(name, body):
            with open(os.path.join(d, name), "wb") as f:
                f.write(body)
        # elfish: 445KB of prototypes, and an address table. Both are facts.
        w("segments.h", b"/* Auto-generated by gen_segments_h.py - do not edit */\n"
                        b"void seg111_0000(CPU *cpu);\nvoid seg112_0000(CPU *cpu);\n")
        w("mem_layout.h", b"/* Auto-generated by gen_image.py. Do not edit. */\n"
                          b"static const uint32_t SEG_SEGMENT_BASE[3] = "
                          b"{16, 65552, 69520};\n")
        # The same header over actual instructions is the copy.
        w("lift_out.c", b"/* Auto-generated by ne_lift.py */\n"
                        b"void f(CPU *cpu) { cpu->al = 0; } /* mov al, 0 */\n")
        # fury3/pod: hand-written, mentions the stubs it replaces, drives the CPU.
        w("shims_impl.c", b"/*\n * Fury3 - hand-written import shims.\n *\n"
                          b" * These replace the auto-generated stubs for imports\n"
                          b" * the MSVC CRT startup depends on.\n */\n"
                          b"#define RECOMP_GENERATED_CODE\n"
                          b"void shim_getenv(CPU *cpu) { cpu->eax = 0; }\n")
        assert not looks_lifted(d, "segments.h"), "declarations are facts"
        assert not looks_lifted(d, "mem_layout.h"), "an address table is a fact"
        assert looks_lifted(d, "lift_out.c")
        assert not looks_lifted(d, "shims_impl.c"), "a shim says so in its header"

    # An image outside docs/ is the game's art until someone says otherwise; one
    # inside docs/ is reported for review rather than trusted, because a
    # screenshot of your renderer and an asset ripped out of the binary are the
    # same kind of file.
    assert ".png" in IMAGE
    for path, bucket in (("docs/img/intro.png", "review"),
                         ("assets/title.png", "game"),
                         ("tools/x.py", None)):
        ext = os.path.splitext(path)[1]
        got = None
        if ext in IMAGE:
            got = "review" if path.startswith("docs/") else "game"
        assert got == bucket, (path, got, bucket)

    # The categories must not overlap, or a file gets counted twice.
    assert not (GAME_BIN & GAME_ASSET)
    assert not (IMAGE & GAME_BIN) and not (IMAGE & GAME_ASSET)

    print("audit_repo.py self-test OK")


if __name__ == "__main__":
    sys.exit(main())
