; difftest64.asm - run one x86-64 instruction on the real CPU.
;
; The differential tester's native half. The lifted half is C generated by
; lift64_cpu.py; this executes the ORIGINAL instruction bytes on the host, from
; the same starting register state, so the two can be compared. That is only
; possible because the host is itself x86-64 - the 32-bit toolchain has to
; emulate its reference, and an emulated reference shares the lifter's
; misconceptions.
;
; Every load and store here is RIP-relative to a global, deliberately: using a
; base register would mean one register could not be set from the input (it
; would be holding the pointer) and could not be captured on the way out. The
; flat form has no such hole, so all fifteen are real on both sides.
;
; RSP is the exception and is not modelled. The instruction under test runs on
; the host stack so that the trailing RET returns here; a guest RSP would have
; to be a scratch stack, and the instructions that care about it - push, pop,
; call, ret - are control flow whose failures are loud. The corpus is register
; and immediate operands, which is where the quiet bugs live: the flags.
;
; MOV does not affect flags, so the input flags are set with POPFQ BEFORE the
; general-purpose registers are loaded. Doing it after would discard them.

OPTION CASEMAP:NONE

EXTERNDEF dt_in:BYTE
EXTERNDEF dt_out:BYTE
EXTERNDEF dt_code:QWORD

; DTSTATE layout, and it must match the C struct in the generated harness:
;   uint64_t gpr[16];   0
;   uint64_t flags;     128
;   uint64_t _pad;      136
;   XMM      xmm[16];   144   (16-byte aligned)
G_RAX   EQU   0
G_RCX   EQU   8
G_RDX   EQU  16
G_RBX   EQU  24
G_RSP   EQU  32
G_RBP   EQU  40
G_RSI   EQU  48
G_RDI   EQU  56
G_R8    EQU  64
G_R9    EQU  72
G_R10   EQU  80
G_R11   EQU  88
G_R12   EQU  96
G_R13   EQU 104
G_R14   EQU 112
G_R15   EQU 120
G_FLAGS EQU 128
G_XMM   EQU 144

.DATA
        ALIGN 16
host_xmm    OWORD 10 DUP(0)         ; xmm6..xmm15 are non-volatile on Win64

.CODE

PUBLIC run_native
; FRAME, and a .PUSHREG for every push, because this procedure needs UNWIND
; INFORMATION - not for tidiness, but because the instruction under test can
; fault, and Windows dispatches an exception by walking unwind data. A PROC
; without it is a hole in the chain: the __except around run_native never runs,
; and the process dies with an access violation and no output at all. That cost
; a debugging session on its own, and only appeared once the corpus included
; memory operands, which are the ones that can fault.
run_native PROC FRAME
        ; ---- preserve the host's non-volatile state ----
        push    rbx
        .pushreg rbx
        push    rbp
        .pushreg rbp
        push    rsi
        .pushreg rsi
        push    rdi
        .pushreg rdi
        push    r12
        .pushreg r12
        push    r13
        .pushreg r13
        push    r14
        .pushreg r14
        push    r15
        .pushreg r15
        .endprolog

        movaps  OWORD PTR [host_xmm + 16*0], xmm6
        movaps  OWORD PTR [host_xmm + 16*1], xmm7
        movaps  OWORD PTR [host_xmm + 16*2], xmm8
        movaps  OWORD PTR [host_xmm + 16*3], xmm9
        movaps  OWORD PTR [host_xmm + 16*4], xmm10
        movaps  OWORD PTR [host_xmm + 16*5], xmm11
        movaps  OWORD PTR [host_xmm + 16*6], xmm12
        movaps  OWORD PTR [host_xmm + 16*7], xmm13
        movaps  OWORD PTR [host_xmm + 16*8], xmm14
        movaps  OWORD PTR [host_xmm + 16*9], xmm15

        ; ---- load the guest XMM file ----
        movups  xmm0,  OWORD PTR [dt_in + G_XMM + 16*0]
        movups  xmm1,  OWORD PTR [dt_in + G_XMM + 16*1]
        movups  xmm2,  OWORD PTR [dt_in + G_XMM + 16*2]
        movups  xmm3,  OWORD PTR [dt_in + G_XMM + 16*3]
        movups  xmm4,  OWORD PTR [dt_in + G_XMM + 16*4]
        movups  xmm5,  OWORD PTR [dt_in + G_XMM + 16*5]
        movups  xmm6,  OWORD PTR [dt_in + G_XMM + 16*6]
        movups  xmm7,  OWORD PTR [dt_in + G_XMM + 16*7]
        movups  xmm8,  OWORD PTR [dt_in + G_XMM + 16*8]
        movups  xmm9,  OWORD PTR [dt_in + G_XMM + 16*9]
        movups  xmm10, OWORD PTR [dt_in + G_XMM + 16*10]
        movups  xmm11, OWORD PTR [dt_in + G_XMM + 16*11]
        movups  xmm12, OWORD PTR [dt_in + G_XMM + 16*12]
        movups  xmm13, OWORD PTR [dt_in + G_XMM + 16*13]
        movups  xmm14, OWORD PTR [dt_in + G_XMM + 16*14]
        movups  xmm15, OWORD PTR [dt_in + G_XMM + 16*15]

        ; ---- flags first: MOV does not disturb them, POPFQ would be undone ----
        push    QWORD PTR [dt_in + G_FLAGS]
        popfq

        ; ---- the fifteen general-purpose registers (RSP excluded) ----
        mov     rax, QWORD PTR [dt_in + G_RAX]
        mov     rcx, QWORD PTR [dt_in + G_RCX]
        mov     rdx, QWORD PTR [dt_in + G_RDX]
        mov     rbx, QWORD PTR [dt_in + G_RBX]
        mov     rbp, QWORD PTR [dt_in + G_RBP]
        mov     rsi, QWORD PTR [dt_in + G_RSI]
        mov     rdi, QWORD PTR [dt_in + G_RDI]
        mov     r8,  QWORD PTR [dt_in + G_R8]
        mov     r9,  QWORD PTR [dt_in + G_R9]
        mov     r10, QWORD PTR [dt_in + G_R10]
        mov     r11, QWORD PTR [dt_in + G_R11]
        mov     r12, QWORD PTR [dt_in + G_R12]
        mov     r13, QWORD PTR [dt_in + G_R13]
        mov     r14, QWORD PTR [dt_in + G_R14]
        mov     r15, QWORD PTR [dt_in + G_R15]

        ; ---- the instruction under test, assembled as <bytes> RET ----
        call    QWORD PTR [dt_code]

        ; ---- capture, flags first, before anything can disturb them ----
        pushfq
        pop     QWORD PTR [dt_out + G_FLAGS]

        mov     QWORD PTR [dt_out + G_RAX], rax
        mov     QWORD PTR [dt_out + G_RCX], rcx
        mov     QWORD PTR [dt_out + G_RDX], rdx
        mov     QWORD PTR [dt_out + G_RBX], rbx
        mov     QWORD PTR [dt_out + G_RBP], rbp
        mov     QWORD PTR [dt_out + G_RSI], rsi
        mov     QWORD PTR [dt_out + G_RDI], rdi
        mov     QWORD PTR [dt_out + G_R8],  r8
        mov     QWORD PTR [dt_out + G_R9],  r9
        mov     QWORD PTR [dt_out + G_R10], r10
        mov     QWORD PTR [dt_out + G_R11], r11
        mov     QWORD PTR [dt_out + G_R12], r12
        mov     QWORD PTR [dt_out + G_R13], r13
        mov     QWORD PTR [dt_out + G_R14], r14
        mov     QWORD PTR [dt_out + G_R15], r15

        movups  OWORD PTR [dt_out + G_XMM + 16*0],  xmm0
        movups  OWORD PTR [dt_out + G_XMM + 16*1],  xmm1
        movups  OWORD PTR [dt_out + G_XMM + 16*2],  xmm2
        movups  OWORD PTR [dt_out + G_XMM + 16*3],  xmm3
        movups  OWORD PTR [dt_out + G_XMM + 16*4],  xmm4
        movups  OWORD PTR [dt_out + G_XMM + 16*5],  xmm5
        movups  OWORD PTR [dt_out + G_XMM + 16*6],  xmm6
        movups  OWORD PTR [dt_out + G_XMM + 16*7],  xmm7
        movups  OWORD PTR [dt_out + G_XMM + 16*8],  xmm8
        movups  OWORD PTR [dt_out + G_XMM + 16*9],  xmm9
        movups  OWORD PTR [dt_out + G_XMM + 16*10], xmm10
        movups  OWORD PTR [dt_out + G_XMM + 16*11], xmm11
        movups  OWORD PTR [dt_out + G_XMM + 16*12], xmm12
        movups  OWORD PTR [dt_out + G_XMM + 16*13], xmm13
        movups  OWORD PTR [dt_out + G_XMM + 16*14], xmm14
        movups  OWORD PTR [dt_out + G_XMM + 16*15], xmm15

        ; ---- restore the host ----
        movaps  xmm6,  OWORD PTR [host_xmm + 16*0]
        movaps  xmm7,  OWORD PTR [host_xmm + 16*1]
        movaps  xmm8,  OWORD PTR [host_xmm + 16*2]
        movaps  xmm9,  OWORD PTR [host_xmm + 16*3]
        movaps  xmm10, OWORD PTR [host_xmm + 16*4]
        movaps  xmm11, OWORD PTR [host_xmm + 16*5]
        movaps  xmm12, OWORD PTR [host_xmm + 16*6]
        movaps  xmm13, OWORD PTR [host_xmm + 16*7]
        movaps  xmm14, OWORD PTR [host_xmm + 16*8]
        movaps  xmm15, OWORD PTR [host_xmm + 16*9]

        pop     r15
        pop     r14
        pop     r13
        pop     r12
        pop     rdi
        pop     rsi
        pop     rbp
        pop     rbx
        ret
run_native ENDP

END
