"""
ne_lift.py - NE-aware 16-bit x86 -> C lifter.

Extends lift16.py with the things a 16-bit Windows/OS-2 binary needs and a
flat DOS MZ does not:

  - NE relocation-aware far-call resolution (internal, import, cross-module)
  - Win16 import calls emitted as MODULE_API(cpu) shims (see ne/win16.py)
  - x87 FPU lifted to native C double operations
  - Segment-aware memory access, CS-relative operands bound to THIS segment

Usage as a library, which is how every project past the default pipeline
drives it:

    import ne_lift
    ne_lift.PREFIX = "mygame"          # names the unreachable-stub helper
    ne_lift.lift_segment(ne, seg_num)  # prints C to stdout

or as a CLI for a quick look at one segment:

    python ne_lift.py <ne_exe> --seg N [--func OFFSET] [--all]

Per-project relocation handling, import bridging and file splitting belong in
the project's own driver, not in a flag here.

History: grown in El-Fish, then Catz, and upstreamed from catz/tools/ne_lift.py
by the World Empire bring-up, which needed it for VBRUN300.DLL and had no
business reaching into another project's directory for it. catz, elfish and
bangbang each still carry a fork that predates this file; they should converge
onto it rather than drift further.
"""

import re
import sys
import os
from typing import Optional

_PC = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'tools', 'tools'))
sys.path.insert(0, os.path.join(_PC, 'disasm'))
sys.path.insert(0, os.path.join(_PC, 'lift'))
sys.path.insert(0, os.path.dirname(__file__))

from decode16 import Decoder, Instruction, OpType, Operand, REG16_NAMES
from lift16 import Lifter, _read, _write, _reg16, _sreg, _mem_addr, _label
from ne_parse import parse_ne, NEHeader, Segment
from ne_decode import disassemble_segment, build_reloc_map
from fpu_decode import decode_fpu, format_fpu
from win16 import get_import, module_name, is_fpu_module


# Project identity for generated code. A driver sets PREFIX before lifting; the
# default keeps output buildable standalone. The unreachable helper is what a
# stub calls when control reaches a block the catalog never lifted -- it must
# abort loudly, because silently returning would hand the caller a frame that is
# wrong from that point on.
PREFIX = 'recomp'
BANNER = 'Auto-generated by ne_lift.py'


def _unreachable_name():
    return f'{PREFIX}_unreachable'


class NELifter(Lifter):
    """Lifts NE executable segments to C code with FPU and relocation support."""

    def __init__(self, ne: NEHeader, seg: Segment):
        super().__init__()
        self.ne = ne
        self.seg = seg
        self.reloc_map = build_reloc_map(seg, ne)
        # Build function name map: (seg_num, offset) -> name
        self.func_names = {}
        # Segment lookup by (possibly offset) index — robust to segment-number
        # remapping used for multi-module recomp (CATZ.WAD segs become 60+).
        self.seg_by_index = {s.index: s for s in ne.segments}
        # Cross-module call resolution: {MODULE_UPPER: {ordinal: (seg, off)}}.
        # Set externally for the host module (CATZ.WAD -> CATZDLL exports).
        self.xmod = {}

    def _resolve_far_call(self, inst: Instruction) -> Optional[str]:
        """Resolve a far call instruction using relocation data."""
        local_off = inst.offset - self.seg.file_offset
        # Check relocations at offset+1 (the operand bytes of CALL far)
        for off in range(local_off, local_off + inst.length):
            if off in self.reloc_map:
                ann = self.reloc_map[off]
                r = ann.reloc
                target_type = r.flags & 3
                if target_type == 0:  # Internal
                    if r.target_seg > 0 and r.target_seg != 0xFF:
                        target = self.seg_by_index.get(r.target_seg)
                        if target is not None and target.is_code:
                            return f'seg{r.target_seg:03d}_{r.target_off:04X}'
                        else:
                            return f'/* data ref seg{r.target_seg}:{r.target_off:04X} */'
                elif target_type in (1, 2):  # Import by ordinal / by name
                    mod = module_name(self.ne, r.module_idx)
                    # Cross-module call into another lifted module (e.g. CATZDLL):
                    # resolve the ordinal to that module's export entry -> function.
                    xm = self.xmod.get(mod.upper())
                    if xm is not None and r.ordinal in xm:
                        s, o = xm[r.ordinal]
                        return f'seg{s:03d}_{o:04X}'
                    imp = get_import(mod, r.ordinal)
                    return imp.name
        return None

    def _get_reloc_at(self, local_off: int) -> Optional[object]:
        """Get relocation annotation at a given local offset."""
        return self.reloc_map.get(local_off)

    def _imm_start(self, inst, m, op1, op2):
        """Byte offset of the instruction's immediate field, or None.

        x86 puts the immediate last, so its position follows from the length.
        This is what separates a relocation on the immediate from one on the
        ModRM displacement -- they live in the same instruction and the lifter
        used to take whichever it found first."""
        immop = None
        if op2 is not None and op2.type in (OpType.IMM8, OpType.IMM16):
            immop = op2
        elif op2 is None and op1 is not None and op1.type in (OpType.IMM8, OpType.IMM16):
            immop = op1
        if immop is None:
            return None
        local_off = inst.offset - self.seg.file_offset
        return local_off + inst.length - (1 if immop.type == OpType.IMM8 else 2)

    def _reloc_offset_value(self, r):
        """OFFSET16 relocation -> the offset it resolves to, or None."""
        if r.src_type != 5:
            return None
        tt = r.flags & 3
        if tt == 0:
            return r.target_off & 0xFFFF
        mod = module_name(self.ne, r.module_idx)
        xm = self.xmod.get(mod.upper())
        if xm and r.ordinal in xm:
            return xm[r.ordinal][1] & 0xFFFF
        return None

    def _resolve_mem_disp(self, inst, m, op1, op2):
        """Apply a relocation sitting on a direct [disp16] memory operand.

        `mov word ptr es:[<fixup>], 1` carries its fixup on the ADDRESS, not the
        value. Lifting it as an immediate wrote the address into the variable and
        left the access pointing at offset 0 -- so a flag written to one place was
        read from another. Rewrite the operand's displacement instead and let the
        normal path emit the access."""
        local_off = inst.offset - self.seg.file_offset
        imm_at = self._imm_start(inst, m, op1, op2)
        for opnd in (op1, op2):
            if opnd is None or opnd.type != OpType.MEM:
                continue
            if opnd.base or opnd.index:
                continue                      # only a bare [disp16] can be fixed up
            for off in range(local_off + 1, local_off + inst.length):
                if imm_at is not None and off == imm_at:
                    continue                  # that one belongs to the immediate
                ann = self._get_reloc_at(off)
                if not ann:
                    continue
                val = self._reloc_offset_value(ann.reloc)
                if val is None:
                    continue
                opnd.disp = val
                return True
        return False

    def lift_instruction(self, inst: Instruction, func_start: int):
        """Override to handle FPU instructions and NE-specific features."""
        m = inst.mnemonic
        op1 = inst.op1
        op2 = inst.op2
        local_off = inst.offset - self.seg.file_offset
        orig = repr(inst)

        # Emit label if this address is a jump target
        self._emit_label(inst.address)

        # A fixup on a direct memory displacement must land on the ADDRESS.
        self._resolve_mem_disp(inst, m, op1, op2)

        # --- FWAIT / NOP are no-ops in our model ---
        # CATZ uses real x87 instructions (not inline FP-emulation trampolines
        # like El-Fish's TSXLIB), so FWAIT/NOP carry no semantics here. (An NOP
        # may host a fixup site, but the fixup target is what matters, not the
        # NOP itself.) Drop them.
        if m in ('wait', 'nop'):
            if m == 'wait':
                return
            if m == 'nop':
                return

        # --- FPU instructions ---
        if m.startswith('f') and not m.startswith('flags'):
            self._lift_fpu(inst, m, orig)
            return

        # --- Far calls with relocation resolution ---
        if m == 'call' and op1 and op1.type == OpType.FAR:
            func_name = self._resolve_far_call(inst)
            if func_name and not func_name.startswith('/*'):
                self._emit(f'push16(cpu, cpu->cs); push16(cpu, 0x{local_off + inst.length:04X});',
                           'far call return addr')
                self._emit(f'{func_name}(cpu);', orig)
            elif func_name:
                self._emit(func_name, orig)
            else:
                self._emit(f'/* unresolved far call {orig} */', orig)
            return

        # --- Indirect far call/jmp through memory (function pointer dispatch) ---
        if m in ('call far', 'jmp far') and op1 and op1.type == OpType.MEM:
            seg_e, off_e = _mem_addr(op1)
            read = (f'uint16_t _o = mem_read16(cpu, {seg_e}, {off_e}); '
                    f'uint16_t _s = mem_read16(cpu, {seg_e}, (uint16_t)({off_e} + 2));')
            if m == 'call far':
                self._emit(f'{{ {read} push16(cpu, cpu->cs); push16(cpu, 0x{local_off + inst.length:04X}); '
                           f'dispatch_far(cpu, _s, _o); }}', orig)
            else:  # jmp far -> tail dispatch
                self._emit(f'{{ {read} dispatch_far(cpu, _s, _o); return; }}', orig)
            return

        # --- Indirect near call/jmp through memory (target in this segment) ---
        if m in ('call', 'jmp') and op1 and op1.type == OpType.MEM:
            seg_e, off_e = _mem_addr(op1)
            idx = self.seg.index
            if m == 'call':
                self._emit(f'{{ uint16_t _o = mem_read16(cpu, {seg_e}, {off_e}); '
                           f'push16(cpu, 0x{local_off + inst.length:04X}); dispatch_near(cpu, {idx}, _o); }}', orig)
            else:  # jmp near indirect -> tail dispatch
                self._emit(f'{{ uint16_t _o = mem_read16(cpu, {seg_e}, {off_e}); '
                           f'dispatch_near(cpu, {idx}, _o); return; }}', orig)
            return

        # --- Near jmp/Jcc to another function in this segment -> tail call ---
        # (base lifter would drop these as "out of function" comments)
        _CC = {'jo': 'cc_o', 'jno': 'cc_no', 'jb': 'cc_b', 'jae': 'cc_ae',
               'je': 'cc_e', 'jne': 'cc_ne', 'jbe': 'cc_be', 'ja': 'cc_a',
               'js': 'cc_s', 'jns': 'cc_ns', 'jp': 'cc_p', 'jnp': 'cc_np',
               'jl': 'cc_l', 'jge': 'cc_ge', 'jle': 'cc_le', 'jg': 'cc_g'}
        if (m == 'jmp' or m in _CC) and op1 and op1.type in (OpType.REL8, OpType.REL16):
            target = op1.disp
            if (target not in self.valid_addrs
                    and target in getattr(self, 'seg_func_offsets', ())):
                callee = f'seg{self.seg.index:03d}_{target:04X}'
                if m == 'jmp':
                    self._emit(f'{callee}(cpu); return;', orig)
                else:
                    self._emit(f'if ({_CC[m]}(cpu)) {{ {callee}(cpu); return; }}', orig)
                return

        # --- loop/jcxz to another function in this segment -> tail call ---
        if m in ('loop', 'loopz', 'loopnz', 'jcxz') and op1 and op1.type in (OpType.REL8, OpType.REL16):
            target = op1.disp
            if (target not in self.valid_addrs
                    and target in getattr(self, 'seg_func_offsets', ())):
                callee = f'seg{self.seg.index:03d}_{target:04X}'
                cond = {'loop': 'cpu->cx != 0',
                        'loopz': 'cpu->cx != 0 && zf(cpu)',
                        'loopnz': 'cpu->cx != 0 && !zf(cpu)',
                        'jcxz': 'cpu->cx == 0'}[m]
                dec = 'cpu->cx--; ' if m != 'jcxz' else ''
                self._emit(f'{dec}if ({cond}) {{ {callee}(cpu); return; }}', orig)
                return

        # --- Far jumps (resolve via relocation -> tail call) ---
        if m == 'jmp' and op1 and op1.type == OpType.FAR:
            func_name = self._resolve_far_call(inst)
            if func_name and not func_name.startswith('/*'):
                # Tail call: run the target, then return to our caller.
                self._emit(f'{func_name}(cpu); return;', orig)
            else:
                self._emit(f'/* unresolved far jmp {orig} */', orig)
            return

        # --- Near calls ---
        if m == 'call' and op1 and op1.type in (OpType.REL8, OpType.REL16):
            target = op1.disp
            # `call $+3` targets the very next instruction: it is not a call at
            # all, it is Borland's "push IP" -- the pushed address is later read
            # back by `pop cx; add cx,3; jmp cx`. Emitting a C call here would
            # run the rest of the function twice (once nested, once via the
            # fall-through) and pop a frame that no longer exists. Push only.
            if target == local_off + inst.length:
                self._emit(f'push16(cpu, 0x{target:04X});', 'push IP (call $+3)')
                return
            func_name = f'seg{self.seg.index:03d}_{target:04X}'
            self.func_calls.add(func_name)
            self._emit(f'push16(cpu, 0x{local_off + inst.length:04X});', 'near call return addr')
            self._emit(f'{func_name}(cpu);', orig)
            return

        # --- Relocated immediates: `mov reg/mem, SELECTOR|OFFSET of symbol` ---
        # The immediate in the original bytes is a placeholder (0xFFFF); the real
        # value comes from the relocation. gen_image patches these in DATA, but
        # the lifted CODE uses the immediate directly, so resolve it here.
        # Covers taking the address of a function/data (incl. cross-module, e.g.
        # a CATZDLL export's offset/selector stored as a WAD callback pointer).
        # `push SEG symbol` carries the same fixup and was NOT covered: the raw
        # 0xFFFF placeholder went straight through, so every far pointer built as
        # `push <selector>; push <offset>` pointed at selector 0xFFFF -- the guard
        # region, where every unmapped access aliases onto every other. The engine
        # passes its WinG BITMAPINFO that way, so the header it filled in was
        # overwritten by an unrelated string before WinGCreateBitmap read it back.
        _reloc_imm = ((m == 'mov' and op2 and op2.type in (OpType.IMM8, OpType.IMM16))
                      or (m == 'push' and op1 and op1.type in (OpType.IMM8, OpType.IMM16)))
        if _reloc_imm:
            _put = ((lambda v: f'push16(cpu, {v});') if m == 'push'
                    else (lambda v: _write(op1, v)))
            _imm_at = self._imm_start(inst, m, op1, op2)
            for off in range(local_off + 1, local_off + inst.length):
                if _imm_at is not None and off != _imm_at:
                    continue          # a displacement fixup, already applied above
                ann = self._get_reloc_at(off)
                if not ann:
                    continue
                r = ann.reloc
                tt = r.flags & 3
                if r.src_type == 2:        # SELECTOR (segment of a symbol)
                    if tt == 0:
                        self._emit(_put(f'SEG_{r.target_seg}'),
                                   f'{orig} -- selector for seg{r.target_seg}')
                        return
                    elif tt in (1, 2):     # cross-module selector (e.g. CATZDLL)
                        mod = module_name(self.ne, r.module_idx)
                        xm = self.xmod.get(mod.upper())
                        if xm and r.ordinal in xm:
                            self._emit(_put(f'SEG_{xm[r.ordinal][0]}'),
                                       f'{orig} -- selector for {mod}.{r.ordinal}')
                            return
                elif r.src_type == 5:      # OFFSET16 (offset of a symbol)
                    # KERNEL.113/114 are __AHSHIFT/__AHINCR: the loader patches
                    # them with how a HUGE pointer steps its selector across a
                    # 64K boundary. Borland emits
                    #     add [off],1 ; adc ax,0 ; mov cl,__AHSHIFT
                    #     shl ax,cl   ; add [sel],ax
                    # Left as the 0xFFFF placeholder, cl became 255, the shift
                    # produced 0, and the selector never advanced -- so every
                    # buffer larger than 64K wrapped over its own start. Real
                    # protected mode uses 3/8 because selectors are 8 apart;
                    # our selectors are consecutive, so the pair is 0/1 and
                    # cpu_alloc_selector tiles a huge block one selector per 64K.
                    if tt in (1, 2) and module_name(self.ne, r.module_idx).upper() == 'KERNEL'                             and r.ordinal in (113, 114):
                        val = 0 if r.ordinal == 113 else 1
                        self._emit(_put(f'0x{val:04X}'),
                                   f'{orig} -- KERNEL.{r.ordinal} '
                                   f'({"__AHSHIFT" if r.ordinal == 113 else "__AHINCR"})')
                        return
                    if tt == 0:
                        self._emit(_put(f'0x{r.target_off & 0xFFFF:04X}'),
                                   f'{orig} -- offset of seg{r.target_seg}:{r.target_off:04X}')
                        return
                    elif tt in (1, 2):
                        mod = module_name(self.ne, r.module_idx)
                        xm = self.xmod.get(mod.upper())
                        if xm and r.ordinal in xm:
                            self._emit(_put(f'0x{xm[r.ordinal][1] & 0xFFFF:04X}'),
                                       f'{orig} -- offset of {mod}.{r.ordinal}')
                            return

        # --- Register-indirect near jmp/call (`jmp cx`) ---
        # The shared lifter drops these entirely — it emits nothing, so the C
        # function falls off its end and RETURNS, skipping everything the guest
        # still had to do. In seg001_2AFC that is Borland's "return to the call
        # site plus 3" trick inside _scanner (`pop cx; add cx,3; jmp cx`), and
        # dropping it made _scanner return straight after its prologue with its
        # frame still allocated — which corrupted bp, then DS, then every far
        # pointer built as `push ds`. Route it through the dispatcher like any
        # other computed near target.
        if m in ('jmp', 'call') and op1 and op1.type == OpType.REG16:
            reg = REG16_NAMES[op1.reg]
            idx = self.seg.index
            if m == 'jmp':
                self._emit(f'dispatch_near(cpu, {idx}, cpu->{reg}); return;', orig)
            else:
                self._emit(f'{{ push16(cpu, 0x{local_off + inst.length:04X}); dispatch_near(cpu, {idx}, cpu->{reg}); }}', orig)
            return

        # --- String ops with a SEGMENT OVERRIDE on the source ---
        # The shared lifter hardcodes cpu->ds for the source of lods/movs/cmps
        # and drops any override prefix. Borland's _vprinter scans its format
        # string with `es: lodsb` (the format is loaded into ES:SI by
        # `les si,[bp+6]`), so with the override dropped every format character
        # is read from the wrong segment and the whole printf family produces
        # garbage. Destination-side (stos/scas, and movs' ES:DI) is always ES
        # and cannot be overridden, so only the source needs fixing.
        # Only intercept when an override is actually present — without one the
        # base lifter is already correct, including its rep handling.
        _STR_SRC = {'lodsb': 1, 'lodsw': 2, 'movsb': 1, 'movsw': 2,
                    'cmpsb': 1, 'cmpsw': 2}
        if m in _STR_SRC and getattr(inst, 'seg_override', ''):
            ov = inst.seg_override
            src = (f'SEG_{self.seg.index}' if ov == 'cs' else f'cpu->{ov}')
            w = _STR_SRC[m]
            step = f'cpu->si += df(cpu) ? -{w} : {w};'
            if m.startswith('lods'):
                reg = 'al' if w == 1 else 'ax'
                body = f'cpu->{reg} = mem_read{w * 8}(cpu, {src}, cpu->si); {step}'
            elif m.startswith('movs'):
                body = (f'mem_write{w * 8}(cpu, cpu->es, cpu->di, '
                        f'mem_read{w * 8}(cpu, {src}, cpu->si)); {step} '
                        f'cpu->di += df(cpu) ? -{w} : {w};')
            else:  # cmps
                body = (f'flags_cmp{w * 8}(cpu, mem_read{w * 8}(cpu, {src}, cpu->si), '
                        f'mem_read{w * 8}(cpu, cpu->es, cpu->di)); {step} '
                        f'cpu->di += df(cpu) ? -{w} : {w};')
            if inst.prefix == 'rep':
                self._emit(f'while (cpu->cx != 0) {{ cpu->cx--; {body} }}',
                           f'rep {orig}')
            elif inst.prefix in ('repz', 'repnz'):
                keep = 'zf(cpu)' if inst.prefix == 'repz' else '!zf(cpu)'
                self._emit(f'while (cpu->cx != 0) {{ cpu->cx--; {body} '
                           f'if (!({keep})) break; }}', f'{inst.prefix} {orig}')
            else:
                self._emit(body, orig)
            return

        # BCD adjust (aam/aad/daa/das) is deliberately NOT overridden here.
        # It used to be: when this file forked, the shared lifter dropped them as
        # stubs, so an inline expansion beat nothing. lift16.py has since grown
        # real bcd_* helpers and the fork went stale -- the inline version emitted
        # `_v / 0` verbatim for `aam 0`, which is UB in C, where bcd_aam guards a
        # zero divisor and leaves AX alone the way the hardware fault does.
        # Deleting the override is the fix.

        # --- Default: delegate to base lifter ---
        super().lift_instruction(inst, func_start)

    def _lift_fpu(self, inst: Instruction, m: str, orig: str):
        """Lift an FPU instruction to C double operations."""
        # The FPU mnemonic may include operands (from fpu_decode.py format_fpu)
        # Parse the mnemonic to extract operation and operands
        parts = m.split(' ', 1)
        op = parts[0]
        operand_str = parts[1] if len(parts) > 1 else ''

        # --- FPU Stack Operations ---
        if op == 'fld':
            if 'st(' in operand_str:
                # fld st(i) - push copy of st(i) onto stack
                i = self._parse_st(operand_str)
                self._emit(f'fpu_push(cpu); cpu->st[0] = cpu->st[{i+1}];', orig)
            elif 'dword' in operand_str or 'qword' in operand_str or 'tword' in operand_str:
                mem_expr = self._fpu_mem_read(inst, operand_str)
                self._emit(f'fpu_push(cpu); cpu->st[0] = {mem_expr};', orig)
            else:
                self._emit(f'/* FPU: {orig} */', orig)

        elif op == 'fst':
            if 'st(' in operand_str:
                i = self._parse_st(operand_str)
                self._emit(f'cpu->st[{i}] = cpu->st[0];', orig)
            elif operand_str:
                mem_expr = self._fpu_mem_write(inst, operand_str, 'cpu->st[0]')
                self._emit(mem_expr, orig)
            else:
                self._emit(f'/* FPU: {orig} */', orig)

        elif op == 'fstp':
            if 'st(' in operand_str:
                i = self._parse_st(operand_str)
                self._emit(f'cpu->st[{i}] = cpu->st[0]; fpu_pop(cpu);', orig)
            elif operand_str:
                mem_expr = self._fpu_mem_write(inst, operand_str, 'cpu->st[0]')
                self._emit(f'{mem_expr} fpu_pop(cpu);', orig)
            else:
                self._emit(f'/* FPU: {orig} */', orig)

        elif op == 'fild':
            mem_expr = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'fpu_push(cpu); cpu->st[0] = (double){mem_expr};', orig)

        elif op == 'fist':
            mem_expr = self._fpu_mem_write_int(inst, operand_str, '(int32_t)cpu->st[0]')
            self._emit(mem_expr, orig)

        elif op == 'fistp':
            mem_expr = self._fpu_mem_write_int(inst, operand_str, '(int32_t)cpu->st[0]')
            self._emit(f'{mem_expr} fpu_pop(cpu);', orig)

        # --- FPU Arithmetic ---
        elif op == 'fadd':
            self._lift_fpu_arith(inst, '+', operand_str, orig)
        elif op == 'faddp':
            self._lift_fpu_arith_pop('+', operand_str, orig)
        elif op == 'fsub':
            self._lift_fpu_arith(inst, '-', operand_str, orig)
        elif op == 'fsubp':
            self._lift_fpu_arith_pop('-', operand_str, orig)
        elif op == 'fsubr':
            self._lift_fpu_arith_r(inst, '-', operand_str, orig)
        elif op == 'fsubrp':
            self._lift_fpu_arith_r_pop('-', operand_str, orig)
        elif op == 'fmul':
            self._lift_fpu_arith(inst, '*', operand_str, orig)
        elif op == 'fmulp':
            self._lift_fpu_arith_pop('*', operand_str, orig)
        elif op == 'fdiv':
            self._lift_fpu_arith(inst, '/', operand_str, orig)
        elif op == 'fdivp':
            self._lift_fpu_arith_pop('/', operand_str, orig)
        elif op == 'fdivr':
            self._lift_fpu_arith_r(inst, '/', operand_str, orig)
        elif op == 'fdivrp':
            self._lift_fpu_arith_r_pop('/', operand_str, orig)

        # --- FPU Integer Arithmetic ---
        elif op == 'fiadd':
            mem = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'cpu->st[0] += (double){mem};', orig)
        elif op == 'fisub':
            mem = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'cpu->st[0] -= (double){mem};', orig)
        elif op == 'fisubr':
            mem = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'cpu->st[0] = (double){mem} - cpu->st[0];', orig)
        elif op == 'fimul':
            mem = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'cpu->st[0] *= (double){mem};', orig)
        elif op == 'fidiv':
            mem = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'cpu->st[0] /= (double){mem};', orig)
        elif op == 'fidivr':
            mem = self._fpu_mem_read_int(inst, operand_str)
            self._emit(f'cpu->st[0] = (double){mem} / cpu->st[0];', orig)

        # --- FPU Compare ---
        elif op == 'fcom':
            if 'st(0), st(' in operand_str:
                i = self._parse_st(operand_str.split('st(0), ')[1])
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[{i}]);', orig)
            elif 'st(' in operand_str:
                i = self._parse_st(operand_str)
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[{i}]);', orig)
            elif operand_str:
                mem = self._fpu_mem_read(inst, operand_str)
                self._emit(f'fpu_compare(cpu, cpu->st[0], {mem});', orig)
            else:
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[1]);', orig)
        elif op == 'fcomp':
            if 'st(0), st(' in operand_str:
                i = self._parse_st(operand_str.split('st(0), ')[1])
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[{i}]); fpu_pop(cpu);', orig)
            elif 'dword' in operand_str or 'qword' in operand_str:
                mem = self._fpu_mem_read(inst, operand_str)
                self._emit(f'fpu_compare(cpu, cpu->st[0], {mem}); fpu_pop(cpu);', orig)
            else:
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[1]); fpu_pop(cpu);', orig)
        elif op == 'fcompp':
            self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[1]); fpu_pop(cpu); fpu_pop(cpu);', orig)
        elif op == 'fprem' or op == 'fprem1':
            self._emit('fpu_prem(cpu);', orig)
        elif op == 'fxam':
            self._emit('fpu_xam(cpu);', orig)
        elif op == 'ftst':
            self._emit(f'fpu_compare(cpu, cpu->st[0], 0.0);', orig)
        elif op == 'fucom':
            if 'st(' in operand_str:
                i = self._parse_st(operand_str)
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[{i}]);', orig)
            else:
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[1]);', orig)
        elif op == 'fucomp':
            if 'st(' in operand_str:
                i = self._parse_st(operand_str)
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[{i}]); fpu_pop(cpu);', orig)
            else:
                self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[1]); fpu_pop(cpu);', orig)
        elif op == 'fucompp':
            self._emit(f'fpu_compare(cpu, cpu->st[0], cpu->st[1]); fpu_pop(cpu); fpu_pop(cpu);', orig)

        # --- FPU Constants ---
        elif op == 'fld1':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 1.0;', orig)
        elif op == 'fldz':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 0.0;', orig)
        elif op == 'fldpi':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 3.14159265358979323846;', orig)
        elif op == 'fldl2e':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 1.44269504088896340736;', orig)
        elif op == 'fldl2t':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 3.32192809488736234787;', orig)
        elif op == 'fldlg2':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 0.30102999566398119521;', orig)
        elif op == 'fldln2':
            self._emit(f'fpu_push(cpu); cpu->st[0] = 0.69314718055994530942;', orig)

        # --- FPU Transcendentals ---
        elif op == 'fsqrt':
            self._emit(f'cpu->st[0] = sqrt(cpu->st[0]);', orig)
        elif op == 'fabs':
            self._emit(f'cpu->st[0] = fabs(cpu->st[0]);', orig)
        elif op == 'fchs':
            self._emit(f'cpu->st[0] = -cpu->st[0];', orig)
        elif op == 'fsin':
            self._emit(f'cpu->st[0] = sin(cpu->st[0]);', orig)
        elif op == 'fcos':
            self._emit(f'cpu->st[0] = cos(cpu->st[0]);', orig)
        elif op == 'fpatan':
            self._emit(f'{{ double _y = cpu->st[1], _x = cpu->st[0]; '
                       f'fpu_pop(cpu); cpu->st[0] = atan2(_y, _x); }}', orig)
        elif op == 'fptan':
            self._emit(f'cpu->st[0] = tan(cpu->st[0]); fpu_push(cpu); cpu->st[0] = 1.0;', orig)
        elif op == 'frndint':
            self._emit(f'cpu->st[0] = rint(cpu->st[0]);', orig)
        elif op == 'fscale':
            self._emit(f'cpu->st[0] = ldexp(cpu->st[0], (int)cpu->st[1]);', orig)
        elif op == 'f2xm1':
            self._emit(f'cpu->st[0] = pow(2.0, cpu->st[0]) - 1.0;', orig)
        elif op == 'fyl2x':
            self._emit(f'{{ double _r = cpu->st[1] * log2(cpu->st[0]); '
                       f'fpu_pop(cpu); cpu->st[0] = _r; }}', orig)
        elif op == 'fyl2xp1':
            self._emit(f'{{ double _r = cpu->st[1] * log2(cpu->st[0] + 1.0); '
                       f'fpu_pop(cpu); cpu->st[0] = _r; }}', orig)

        # --- FPU Control ---
        elif op == 'fxch':
            if 'st(' in operand_str:
                i = self._parse_st(operand_str)
                self._emit(f'{{ double _t = cpu->st[0]; cpu->st[0] = cpu->st[{i}]; '
                           f'cpu->st[{i}] = _t; }}', orig)
            else:
                self._emit(f'{{ double _t = cpu->st[0]; cpu->st[0] = cpu->st[1]; '
                           f'cpu->st[1] = _t; }}', orig)
        elif op == 'ffree':
            self._emit(f'/* ffree {operand_str} */', orig)
        elif op == 'finit' or op == 'fninit':
            self._emit(f'fpu_init(cpu);', orig)
        elif op == 'fclex' or op == 'fnclex':
            self._emit(f'cpu->fpu_status &= 0x7F00;', orig)
        elif op == 'fldcw':
            self._emit(f'/* fldcw - load FPU control word */', orig)
        elif op == 'fstcw' or op == 'fnstcw':
            self._emit(f'/* fstcw - store FPU control word */', orig)
        elif op == 'fstsw' or op == 'fnstsw':
            if 'ax' in operand_str:
                self._emit(f'cpu->ax = cpu->fpu_status;', orig)
            else:
                # `fstsw m16` was emitted as a bare comment, so the status word
                # never reached memory. Borland's x87 compare idiom is
                #   fcomp ...; fstsw [bp-N]; mov ax,[bp-N]; sahf; jbe
                # so the following `mov ax` read a stale stack local and EVERY
                # float comparison in the engine branched on garbage -- which is
                # what put the pet's geometry (and so its screen position) wrong.
                seg, off = self._fpu_mem_expr(inst, operand_str)
                self._emit(f'mem_write16(cpu, {seg}, {off}, cpu->fpu_status);', orig)
        elif op == 'fdecstp':
            self._emit(f'cpu->fpu_top = (cpu->fpu_top - 1) & 7;', orig)
        elif op == 'fincstp':
            self._emit(f'cpu->fpu_top = (cpu->fpu_top + 1) & 7;', orig)
        elif op == 'fnop':
            self._emit(f'/* fnop */', orig)

        # --- Catch-all ---
        else:
            self._emit(f'/* FPU TODO: {orig} */', orig)

    def _lift_fpu_arith(self, inst, op: str, operand_str: str, orig: str):
        """Lift FPU arithmetic: fadd/fsub/fmul/fdiv."""
        if 'st(0), st(' in operand_str:
            i = self._parse_st(operand_str.split('st(0), ')[1])
            self._emit(f'cpu->st[0] = cpu->st[0] {op} cpu->st[{i}];', orig)
        elif 'st(' in operand_str and '), st(0)' in operand_str:
            i = self._parse_st(operand_str)
            self._emit(f'cpu->st[{i}] = cpu->st[{i}] {op} cpu->st[0];', orig)
        elif operand_str:
            mem = self._fpu_mem_read(inst, operand_str)
            self._emit(f'cpu->st[0] = cpu->st[0] {op} {mem};', orig)
        else:
            self._emit(f'cpu->st[0] = cpu->st[0] {op} cpu->st[1];', orig)

    def _lift_fpu_arith_pop(self, op: str, operand_str: str, orig: str):
        """Lift FPU arithmetic with pop: faddp/fsubp/fmulp/fdivp."""
        if 'st(' in operand_str:
            i = self._parse_st(operand_str)
            self._emit(f'cpu->st[{i}] = cpu->st[{i}] {op} cpu->st[0]; fpu_pop(cpu);', orig)
        else:
            self._emit(f'cpu->st[1] = cpu->st[1] {op} cpu->st[0]; fpu_pop(cpu);', orig)

    def _lift_fpu_arith_r(self, inst, op: str, operand_str: str, orig: str):
        """Lift FPU reverse arithmetic: fsubr/fdivr."""
        if 'st(0), st(' in operand_str:
            i = self._parse_st(operand_str.split('st(0), ')[1])
            self._emit(f'cpu->st[0] = cpu->st[{i}] {op} cpu->st[0];', orig)
        elif operand_str:
            mem = self._fpu_mem_read(inst, operand_str)
            self._emit(f'cpu->st[0] = {mem} {op} cpu->st[0];', orig)
        else:
            self._emit(f'cpu->st[0] = cpu->st[1] {op} cpu->st[0];', orig)

    def _lift_fpu_arith_r_pop(self, op: str, operand_str: str, orig: str):
        """Lift FPU reverse arithmetic with pop."""
        if 'st(' in operand_str:
            i = self._parse_st(operand_str)
            self._emit(f'cpu->st[{i}] = cpu->st[0] {op} cpu->st[{i}]; fpu_pop(cpu);', orig)
        else:
            self._emit(f'cpu->st[1] = cpu->st[0] {op} cpu->st[1]; fpu_pop(cpu);', orig)

    def _parse_st(self, operand_str: str) -> int:
        """Extract register number from st(N) pattern, ignoring extra operands."""
        import re
        m = re.search(r'st\((\d+)\)', operand_str)
        return int(m.group(1)) if m else 0

    def _fpu_mem_expr(self, inst, operand_str: str) -> tuple:
        """Get (seg_expr, off_expr) for FPU memory operand.
        Uses inst.op1 if available (preserved from ModR/M decode), otherwise falls back."""
        if inst and inst.op1 and inst.op1.type in (OpType.MEM, OpType.MOFFS):
            seg, off = _mem_addr(inst.op1)
            return seg, off
        # Fallback: can't resolve, emit a comment
        return 'cpu->ds', f'0 /* TODO: {operand_str} */'

    def _fpu_mem_read(self, inst, operand_str: str) -> str:
        """Generate C expression to read FPU memory operand as double."""
        seg, off = self._fpu_mem_expr(inst, operand_str)
        if 'qword' in operand_str:
            return f'fpu_read_f64(cpu, {seg}, {off})'
        elif 'tword' in operand_str:
            return f'fpu_read_f80(cpu, {seg}, {off})'
        else:  # dword
            return f'fpu_read_f32(cpu, {seg}, {off})'

    def _fpu_mem_write(self, inst, operand_str: str, value: str) -> str:
        """Generate C statement to write FPU value to memory."""
        seg, off = self._fpu_mem_expr(inst, operand_str)
        if 'qword' in operand_str:
            return f'fpu_write_f64(cpu, {seg}, {off}, {value});'
        elif 'tword' in operand_str:
            return f'fpu_write_f80(cpu, {seg}, {off}, {value});'
        else:  # dword
            return f'fpu_write_f32(cpu, {seg}, {off}, {value});'

    def _fpu_mem_read_int(self, inst, operand_str: str) -> str:
        """Generate C expression to read FPU integer memory operand."""
        seg, off = self._fpu_mem_expr(inst, operand_str)
        if 'qword' in operand_str:
            return f'fpu_read_i64(cpu, {seg}, {off})'
        if 'dword' in operand_str:
            return f'fpu_read_i32(cpu, {seg}, {off})'
        else:  # word
            return f'fpu_read_i16(cpu, {seg}, {off})'

    def _fpu_mem_write_int(self, inst, operand_str: str, value: str) -> str:
        """Generate C statement to write integer to FPU memory."""
        seg, off = self._fpu_mem_expr(inst, operand_str)
        if 'qword' in operand_str:
            # 64-bit; the caller's `value` is narrowed to int32, so redo the cast
            return f'fpu_write_i64(cpu, {seg}, {off}, (int64_t)cpu->st[0]);'
        if 'dword' in operand_str:
            return f'fpu_write_i32(cpu, {seg}, {off}, {value});'
        else:  # word
            return f'fpu_write_i16(cpu, {seg}, {off}, {value});'


def lift_segment(ne: NEHeader, seg_num: int, func_offset: int = -1, xmod=None):
    """Lift functions from a segment to C code. `xmod` (optional) maps a module
    name to {ordinal: (seg, off)} for cross-module call resolution (host->DLL)."""
    seg = next((s for s in ne.segments if s.index == seg_num), None)
    if not seg or not seg.is_code:
        print(f"Error: segment {seg_num} not found or not CODE")
        return

    instructions, functions, reloc_map = disassemble_segment(seg, ne)

    if not functions:
        print(f"/* No functions detected in segment {seg_num} */")
        return

    # Header
    print(f'/* Segment {seg_num} - {seg.actual_size} bytes, {len(functions)} functions */')
    print(f'/* {BANNER} */')
    print()
    print('#include "segments.h"')
    print()

    # CS-relative memory operands must read from THIS segment, not runtime cpu->cs.
    import lift16
    lift16._CODE_SEG = seg.index

    # Lift each function
    lifter = NELifter(ne, seg)
    lifter.xmod = xmod or {}
    # Function entry offsets in this segment, for near-jmp-to-another-function.
    lifter.seg_func_offsets = {f.offset for f in functions}

    target_funcs = functions
    if func_offset >= 0:
        target_funcs = [f for f in functions if f.offset == func_offset]
        if not target_funcs:
            print(f"/* Function at offset 0x{func_offset:04X} not found */")
            return

    # Map each function start offset to its label, for fall-through handling.
    off_to_label = {f.offset: f.label for f in functions}
    valid_labels = {f.label for f in functions}
    TERMINATORS = ('ret', 'retf', 'iret', 'jmp')

    for func in target_funcs:
        # Get instructions for this function
        func_insts = [i for i in instructions
                      if func.offset <= (i.offset - seg.file_offset) < func.end]
        if not func_insts:
            # A branch target that landed inside an instruction: detect_functions
            # made a label for it but there is nothing to lift. This only happens
            # inside runs of data the sweep decoded as code, so the branch never
            # executes -- emit a body that says so rather than leaving the label
            # undefined and breaking the link.
            print('void ' + func.label + '(CPU *cpu)\n{\n' + '    TRACE_FN(\"' + func.label + '\");\n' + '    ' + _unreachable_name() + '(\"%03d\", 0x%04X);\n' % (seg.index, func.offset) + '}\n')
            continue

        code = lifter.lift_function(
            func.label, func_insts, seg.file_offset + func.offset, func.is_far)
        # Inject an entry-trace marker (compiles to nothing without -DELFISH_TRACE_FN)
        code = code.replace('{\n', '{\n    TRACE_FN("%s");\n' % func.label, 1)

        # Drop lift16's own fall-through line. It resolves the next address as a
        # real-mode seg:off pair (`recomp_dispatch(cpu, addr>>4, addr&0xF)`),
        # which is meaningless for NE protected mode — segments are selectors,
        # not paragraphs. We emit the correct label-based fall-through below.
        code = '\n'.join(l for l in code.split('\n') if '/* fallthrough 0x' not in l)

        # Same for its tail-jcc form. These are branches whose target we could
        # not decode at all (typically a target past the end of the segment,
        # reached only from a mis-decoded byte run), so there is no label to
        # jump to. Make it explicit and loud instead of emitting a call to an
        # undeclared real-mode dispatcher.
        def _unreachable(m):
            addr = (int(m.group(1), 16) << 4) | int(m.group(2), 16)
            return (f'{_unreachable_name()}("{seg.index:03d}", 0x{addr - seg.file_offset:04X});'
                    f' return; /* unlifted branch target */')
        code = re.sub(r'recomp_dispatch\(cpu, 0x([0-9A-Fa-f]+), 0x([0-9A-Fa-f]+)\); return;',
                      _unreachable, code)

        # A branch into the middle of an instruction has no label to jump to.
        # These only arise inside runs of data that the sweep decoded as code, so
        # the branch is never actually executed -- but it still has to compile.
        # Any same-segment callee we did not lift becomes an unreachable stub.
        def _unknown_label(m):
            if m.group(1) in valid_labels:
                return m.group(0)
            return (f'{_unreachable_name()}("{seg.index:03d}", 0x{m.group(2)});'
                    f' return; /* branch into mid-instruction */')
        code = re.sub(rf'(seg{seg.index:03d}_([0-9A-F]{{4}}))\(cpu\); return;',
                      _unknown_label, code)

        # Fall-through: if the last instruction is not a control-flow terminator,
        # execution flows into the next function. Emit that as a tail call so the
        # control flow isn't lost at the function boundary.
        last = func_insts[-1]
        if last.mnemonic not in TERMINATORS:
            nxt = off_to_label.get(func.end)
            if nxt and nxt != func.label:
                close = code.rfind('}')
                code = (code[:close]
                        + f'    {nxt}(cpu); return; /* fall-through */\n'
                        + code[close:])

        print(code)
        print()


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <ne_exe> --seg N [--func OFFSET]")
        sys.exit(1)

    filepath = sys.argv[1]
    ne = parse_ne(filepath)

    if '--seg' not in sys.argv:
        print("Error: --seg N required")
        sys.exit(1)

    idx = sys.argv.index('--seg')
    seg_num = int(sys.argv[idx + 1])

    func_offset = -1
    if '--func' in sys.argv:
        idx = sys.argv.index('--func')
        func_offset = int(sys.argv[idx + 1], 0)

    lift_segment(ne, seg_num, func_offset)


if __name__ == '__main__':
    main()
