"""
gen_segments_h.py - Regenerate segments.h from lifted NE sources.

Scans the lifted `void segNNN_XXXX(CPU *cpu)` definitions and emits matching
prototypes, plus one selector placeholder per NE segment. Generating the
prototypes from the definitions is the point: they cannot drift, so every
cross-segment call resolves at link time or fails loudly at generation.

    python gen_segments_h.py --src work/src --out runtime/segments.h \
                             --ne original/ex/GAME.DLL

--ne is optional and only sets how many SEG_n placeholders to emit; without it
the highest segment number seen in the sources is used.

Upstreamed from catz/tools/, where the segment count and include guard were
hardcoded.
"""
import argparse
import glob
import os
import re
import sys

DEF_RE = re.compile(r"^void (seg\d+_[0-9A-Fa-f]+)\(CPU \*cpu\)", re.M)


def collect(src_dir):
    """{segment number: [function names]}, first definition of a name wins."""
    by_seg, seen = {}, set()
    for path in sorted(glob.glob(os.path.join(src_dir, "*.c"))):
        text = open(path, encoding="utf-8", errors="replace").read()
        for name in DEF_RE.findall(text):
            if name in seen:
                continue
            seen.add(name)
            by_seg.setdefault(int(name[3:name.index("_")]), []).append(name)
    return by_seg


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="directory of lifted seg*.c")
    ap.add_argument("--out", required=True, help="segments.h to write")
    ap.add_argument("--ne", help="the NE binary, to size the selector table")
    ap.add_argument("--guard", default="RECOMP_SEGMENTS_H")
    args = ap.parse_args()

    by_seg = collect(args.src)
    if not by_seg:
        sys.exit(f"no lifted functions found in {args.src}")

    max_seg = max(by_seg)
    if args.ne:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        from ne_parse import parse_ne
        max_seg = max(max_seg, max(s.index for s in parse_ne(args.ne).segments))

    L = ["/* segments.h - forward declarations for every lifted function */",
         "/* Auto-generated by gen_segments_h.py - do not edit manually */",
         "", f"#ifndef {args.guard}", f"#define {args.guard}", "",
         '#include "cpu.h"', '#include "runtime_api.h"', "",
         "/* ---- SEGMENT SELECTOR PLACEHOLDERS ----",
         " * Protected-mode NE selectors map to flat-memory bases at runtime.",
         " * Placeholder: selector == NE segment index. Replace with a real",
         " * selector->base table when the protected-mode memory model lands. */"]
    L += [f"#define SEG_{n} ((uint16_t){n})" for n in range(1, max_seg + 1)]
    L.append("")

    total = 0
    for seg in sorted(by_seg):
        names = by_seg[seg]
        L.append(f"/* seg{seg:03d} ({len(names)} functions) */")
        L += [f"void {n}(CPU *cpu);" for n in names]
        L.append("")
        total += len(names)
    L.append(f"#endif /* {args.guard} */")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L) + "\n")
    print(f"Wrote {args.out}: {total} prototypes across {len(by_seg)} segments, "
          f"{max_seg} selectors")


if __name__ == "__main__":
    main()
