"""
gen_win16_stubs.py - Emit a Win16 NE binary's import surface as C.

Reads the target's own relocations and writes two files, so the shim layer can
never drift from what the binary actually imports:

  <api-header>   prototypes for every import, plus the indirect dispatchers and
                 the INT handlers, each annotated with its PASCAL purge
  <stubs.c>      a default body for every import with NO hand-written shim in
                 the shim directory

The contract every shim obeys, generated or hand-written, matches what
tools/lift/lift16.py (via a project's NE lifter) emits at a far call:

    push16(cs); push16(ret_off); MODULE_API(cpu);

so a shim pops 4 bytes of far return address plus its PASCAL argument purge
(win16.PURGE), returns WORD in AX and DWORD in DX:AX, and returns normally -
there is no RETF to execute, the C return IS the RETF.

A generated stub still purges correctly and says so once, so an unimplemented
call announces itself instead of silently returning garbage and shifting its
caller's frame.

Usage:
    python gen_win16_stubs.py GAME.DLL --api runtime/runtime_api.h \\
        --stubs runtime/win16/win16_stubs.c --shims runtime/win16 \\
        --guard MYGAME
"""
import argparse
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ne_parse import parse_ne
import win16

# A hand-written shim is any `void MODULE_API(CPU *cpu)` definition in the shim
# directory, other than the generated stub file itself.
DEF_RE = re.compile(r'^void ([A-Z0-9_]+)\(CPU \*cpu\)', re.M)


def imports_used(ne):
    """Every distinct import the binary's relocations reference.

    Returns {shim_name: (Win16Import, called)}. `called` is False for imports
    that only ever appear as OFFSET16 relocations - __AHSHIFT, __AHINCR and
    __WINFLAGS are absolute VALUES the loader patches into the code stream, not
    routines, and a stub that unwound a frame for one would corrupt the caller.
    """
    seen = {}
    for seg in ne.segments:
        for r in seg.relocations:
            if (r.flags & 3) not in (1, 2):
                continue
            imp = win16.get_import(win16.module_name(ne, r.module_idx), r.ordinal)
            entry = seen.setdefault(imp.name, [imp, False])
            if r.src_type != 5:
                entry[1] = True
    return seen


def hand_written(shim_dir, stubs_path):
    names = set()
    for path in glob.glob(os.path.join(shim_dir, '*.c')):
        if os.path.abspath(path) == os.path.abspath(stubs_path):
            continue
        names.update(DEF_RE.findall(
            open(path, encoding='utf-8', errors='replace').read()))
    return names


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('binary', help='the NE executable or DLL being lifted')
    ap.add_argument('--api', required=True, help='runtime_api.h to write')
    ap.add_argument('--stubs', required=True, help='win16_stubs.c to write')
    ap.add_argument('--shims', help='directory of hand-written shims '
                                    '(default: the stubs file directory)')
    ap.add_argument('--guard', default='RECOMP', help='include-guard prefix')
    args = ap.parse_args()

    shim_dir = args.shims or os.path.dirname(args.stubs) or '.'
    ne = parse_ne(args.binary)
    used = imports_used(ne)
    have = hand_written(shim_dir, args.stubs)

    by_mod = {}
    for name, (imp, called) in used.items():
        by_mod.setdefault(imp.module, []).append((name, imp, called))

    target = os.path.basename(args.binary)
    guard = args.guard.upper()

    # ---- the API header ----
    h = ['/* runtime_api.h - Auto-generated by gen_win16_stubs.py. Do not edit. */',
         f'/* Host entry points the lifted {target} code calls: indirect-call',
         ' * dispatchers, INT handlers, and the Win16 import shims. */',
         f'#ifndef {guard}_RUNTIME_API_H',
         f'#define {guard}_RUNTIME_API_H',
         '',
         '#include "cpu.h"',
         '',
         '/* ---- Indirect call dispatchers (function pointers) ---- */',
         'void dispatch_far(CPU *cpu, uint16_t seg, uint16_t off);',
         'void dispatch_near(CPU *cpu, uint16_t seg, uint16_t off);',
         '',
         '/* ---- Software interrupts ---- */',
         'void int_handler(CPU *cpu, int int_num);',
         'void dos_int21(CPU *cpu);',
         '',
         f'/* ---- Win16 import shims ({len(used)} total) ---- */']
    unknown_purge = []
    for mod in sorted(by_mod):
        entries = sorted(by_mod[mod])
        h.append('')
        h.append(f'/* {mod} ({len(entries)}) */')
        for name, imp, called in entries:
            purge = win16.get_purge(imp.module, imp.api)
            if called and purge is None:
                unknown_purge.append(f'{imp.module}.{imp.api} (@{imp.ordinal})')
            kind = f'purge {purge}' if called else 'absolute value, not called'
            h.append(f'void {name}(CPU *cpu);  /* @{imp.ordinal} {imp.api}, {kind} */')
    h += ['', f'#endif /* {guard}_RUNTIME_API_H */']
    os.makedirs(os.path.dirname(os.path.abspath(args.api)), exist_ok=True)
    with open(args.api, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(h) + '\n')

    # ---- the generated stubs ----
    c = ['/* win16_stubs.c - Auto-generated by gen_win16_stubs.py. Do not edit. */',
         '/* Default body for every import with no hand-written shim: purge the  */',
         '/* frame correctly, return 0, and say so once so an unimplemented call */',
         '/* announces itself instead of silently returning garbage.             */',
         '',
         '#include <stdio.h>',
         '#include "cpu.h"',
         '#include "runtime_api.h"',
         '',
         'static void unimpl(CPU *cpu, const char *api, int purge)',
         '{',
         '    static const char *seen[256];',
         '    static int nseen;',
         '    int i;',
         '    for (i = 0; i < nseen; i++)',
         '        if (seen[i] == api) break;',
         '    if (i == nseen && nseen < 256) {',
         '        seen[nseen++] = api;',
         '        fprintf(stderr, "[win16] unimplemented: %s\\n", api);',
         '    }',
         '    cpu->ax = 0; cpu->dx = 0;',
         '    cpu->sp = (uint16_t)(cpu->sp + 4 + purge);   /* far retaddr + PASCAL args */',
         '}',
         '']
    generated = 0
    for mod in sorted(by_mod):
        for name, imp, called in sorted(by_mod[mod]):
            if name in have:
                continue
            if not called:
                msg = f'[win16] {imp.api} called, but it is an absolute value import'
                c.append(f'void {name}(CPU *cpu) {{ (void)cpu; '
                         f'fprintf(stderr, "{msg}\\n"); }}')
            else:
                purge = win16.get_purge(imp.module, imp.api)
                c.append(f'void {name}(CPU *cpu) {{ '
                         f'unimpl(cpu, "{imp.module}.{imp.api}", {purge if purge is not None else 0}); }}')
            generated += 1
    c.append('')
    os.makedirs(os.path.dirname(os.path.abspath(args.stubs)), exist_ok=True)
    with open(args.stubs, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(c) + '\n')

    print(f'{args.api}: {len(used)} imports across {len(by_mod)} modules')
    print(f'{args.stubs}: {generated} generated, {len(used) - generated} hand-written')
    for mod in sorted(by_mod):
        n = len(by_mod[mod])
        hw = sum(1 for name, _, _ in by_mod[mod] if name in have)
        print(f'  {mod:<10s} {n:3d}  ({hw} hand-written)')

    if unknown_purge:
        # Not a warning to skim past. Win16 is PASCAL: a shim that pops the
        # wrong number of bytes shifts its CALLER's frame, so the crash lands
        # far from here. Add the entries to win16.PURGE before running.
        print(f'\n{len(unknown_purge)} imports have NO purge value - the frame '
              f'will be wrong at every one of these call sites:', file=sys.stderr)
        for item in sorted(set(unknown_purge)):
            print(f'  {item}', file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
