"""
gen_unresolved_stubs.py - Define the cross-segment call targets nothing lifted.

A linear sweep desyncs on data embedded in code, so some call targets land
mid-instruction and never become a lifted function. Other lifted code still
calls `segNNN_XXXX(cpu)`, and the link fails on the undefined symbol. This
defines each one so the program links.

The stub aborts. It does NOT return.

That is the whole point, and it is where this differs from the catz version it
was upstreamed from, which emitted `{ (void)cpu; }`. A no-op stub returns to a
caller that believes the call did its work: the guest carries on with a frame
and registers that are wrong from that point on, and the failure surfaces
somewhere else entirely, in code that is fine. The same reasoning
gen_win16_stubs.py already applies to an unimplemented import applies here.

    python gen_unresolved_stubs.py --src work/src --out work/src/_unresolved_stubs.c

Every stub is a coverage gap. The count is the number to drive down; the real
fix is aligning those targets, not defining them.
"""
import argparse
import glob
import os
import re

DEF_RE = re.compile(r"^void (seg\d+_[0-9A-Fa-f]+)\(CPU \*cpu\)", re.M)
CALL_RE = re.compile(r"\b(seg\d+_[0-9A-Fa-f]+)\(cpu\)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True, help="directory of lifted seg*.c")
    ap.add_argument("--out", required=True, help="the .c file to write")
    ap.add_argument("--prefix", default="recomp",
                    help="matches ne_lift.PREFIX; names the abort helper")
    args = ap.parse_args()

    out_abs = os.path.abspath(args.out)
    defined, called = set(), set()
    for path in sorted(glob.glob(os.path.join(args.src, "*.c"))):
        if os.path.abspath(path) == out_abs:
            continue
        text = open(path, encoding="utf-8", errors="replace").read()
        defined.update(DEF_RE.findall(text))
        called.update(CALL_RE.findall(text))

    undefined = sorted(called - defined)

    L = [f"/* _unresolved_stubs.c - Auto-generated by gen_unresolved_stubs.py */",
         "/* Call targets the disassembler could not align to an instruction    */",
         "/* boundary (data-in-code desync). Each one aborts rather than return */",
         "/* silently, because a silent return corrupts the caller from here on.*/",
         "",
         '#include "segments.h"',
         ""]
    for name in undefined:
        seg, off = name[3:name.index("_")], name[name.index("_") + 1:]
        L.append(f'void {name}(CPU *cpu) {{ (void)cpu; '
                 f'{args.prefix}_unreachable("{seg}", 0x{off}); }}')
    L.append("")

    os.makedirs(os.path.dirname(out_abs), exist_ok=True)
    with open(out_abs, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(L))

    print(f"Wrote {args.out}: {len(undefined)} unresolved stubs "
          f"({len(defined)} lifted functions, {len(called)} distinct call targets, "
          f"{100.0 * len(undefined) / max(1, len(called)):.2f}% unresolved)")


if __name__ == "__main__":
    main()
